/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface CampaignFactoryInterface extends utils.Interface {
  contractName: "CampaignFactory";
  functions: {
    "campaignAddress(address,bytes32)": FunctionFragment;
    "createErc20Campaign(bytes32,bytes32,bytes32,address,address,bytes32,address)": FunctionFragment;
    "createEthCampaign(bytes32,bytes32,bytes32,address,address,bytes32)": FunctionFragment;
    "erc20CampaignAddress(bytes32)": FunctionFragment;
    "ethCampaignAddress(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "campaignAddress",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createErc20Campaign",
    values: [BytesLike, BytesLike, BytesLike, string, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createEthCampaign",
    values: [BytesLike, BytesLike, BytesLike, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "erc20CampaignAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ethCampaignAddress",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "campaignAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createErc20Campaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEthCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20CampaignAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethCampaignAddress",
    data: BytesLike
  ): Result;

  events: {
    "Erc20CampaignCreated(address,address,bytes32,bytes32,bytes32,address,address,address,bytes32)": EventFragment;
    "EthCampaignCreated(address,address,bytes32,bytes32,bytes32,address,address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Erc20CampaignCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthCampaignCreated"): EventFragment;
}

export type Erc20CampaignCreatedEvent = TypedEvent<
  [string, string, string, string, string, string, string, string, string],
  {
    creator: string;
    newCampaign: string;
    _sharesMerkleRoot: string;
    _sharesUri: string;
    _strategyUri: string;
    _guardian: string;
    _oracle: string;
    _rewardToken: string;
    salt: string;
  }
>;

export type Erc20CampaignCreatedEventFilter =
  TypedEventFilter<Erc20CampaignCreatedEvent>;

export type EthCampaignCreatedEvent = TypedEvent<
  [string, string, string, string, string, string, string, string],
  {
    creator: string;
    newCampaign: string;
    _sharesMerkleRoot: string;
    _sharesUri: string;
    _strategyUri: string;
    _guardian: string;
    _oracle: string;
    salt: string;
  }
>;

export type EthCampaignCreatedEventFilter =
  TypedEventFilter<EthCampaignCreatedEvent>;

export interface CampaignFactory extends BaseContract {
  contractName: "CampaignFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CampaignFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    campaignAddress(
      master: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createErc20Campaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      _rewardToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createEthCampaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    erc20CampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ethCampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  campaignAddress(
    master: string,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  createErc20Campaign(
    _sharesMerkleRoot: BytesLike,
    _sharesUri: BytesLike,
    _strategyUri: BytesLike,
    _guardian: string,
    _oracle: string,
    salt: BytesLike,
    _rewardToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createEthCampaign(
    _sharesMerkleRoot: BytesLike,
    _sharesUri: BytesLike,
    _strategyUri: BytesLike,
    _guardian: string,
    _oracle: string,
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  erc20CampaignAddress(
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  ethCampaignAddress(
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    campaignAddress(
      master: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    createErc20Campaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      _rewardToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createEthCampaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    erc20CampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    ethCampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "Erc20CampaignCreated(address,address,bytes32,bytes32,bytes32,address,address,address,bytes32)"(
      creator?: null,
      newCampaign?: null,
      _sharesMerkleRoot?: null,
      _sharesUri?: null,
      _strategyUri?: null,
      _guardian?: null,
      _oracle?: null,
      _rewardToken?: null,
      salt?: null
    ): Erc20CampaignCreatedEventFilter;
    Erc20CampaignCreated(
      creator?: null,
      newCampaign?: null,
      _sharesMerkleRoot?: null,
      _sharesUri?: null,
      _strategyUri?: null,
      _guardian?: null,
      _oracle?: null,
      _rewardToken?: null,
      salt?: null
    ): Erc20CampaignCreatedEventFilter;

    "EthCampaignCreated(address,address,bytes32,bytes32,bytes32,address,address,bytes32)"(
      creator?: null,
      newCampaign?: null,
      _sharesMerkleRoot?: null,
      _sharesUri?: null,
      _strategyUri?: null,
      _guardian?: null,
      _oracle?: null,
      salt?: null
    ): EthCampaignCreatedEventFilter;
    EthCampaignCreated(
      creator?: null,
      newCampaign?: null,
      _sharesMerkleRoot?: null,
      _sharesUri?: null,
      _strategyUri?: null,
      _guardian?: null,
      _oracle?: null,
      salt?: null
    ): EthCampaignCreatedEventFilter;
  };

  estimateGas: {
    campaignAddress(
      master: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createErc20Campaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      _rewardToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createEthCampaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    erc20CampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ethCampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    campaignAddress(
      master: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createErc20Campaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      _rewardToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createEthCampaign(
      _sharesMerkleRoot: BytesLike,
      _sharesUri: BytesLike,
      _strategyUri: BytesLike,
      _guardian: string,
      _oracle: string,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    erc20CampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ethCampaignAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
